name: soda

services:
  soda_app:
    image: soda:latest
    ports:
      - 3030:3030
    environment:
      SODA_SYSTEM_DB_USER: root
      SODA_SYSTEM_DB_PASSWORD: password
      SODA_SYSTEM_DB_ADDR: soda_db:3306
      SODA_SYSTEM_DB_NAME: soda
    depends_on:
      soda_db:
        condition: service_healthy
        restart: true
  soda_db:  
    image: mysql:9.1
    volumes:
      - soda-mysql-data:/var/lib/mysql
      - ./docker/init.d/db:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DB: soda
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
volumes:
  soda-mysql-data: